import type { Application } from "./types";

export const applications: Application[] = [
  { id:"app-001", candidate:"Fabrina Silva", company:"The Hermitage", role:"Guest Services Agent", country:"Nova Zelândia", countryCode:"NZ", city:"Aoraki / Mount Cook", appliedAt:"2026-09-25", status:"Aguardando", email:"reservations@hermitage.co.nz", stage:"Etapa 4", followUpAt:"2026-10-02", source:"Email", cv:"Fabrina_Silva_CV_Hermitage_New_Zealand.pdf" },
  { id:"app-002", candidate:"Fabrina Silva", company:"Corinthia Palace", role:"Reservations Agent", country:"Malta", countryCode:"MT", city:"Attard", appliedAt:"2026-09-25", status:"Aguardando", email:"hr.palace@corinthia.com", stage:"Etapa 4", followUpAt:"2026-10-02", source:"Email", cv:"Fabrina_Silva_CV_beHOTEL_Malta.pdf" },
  { id:"app-003", candidate:"Fabrina Silva", company:"The Westin Dragonara Resort", role:"Service Express Agent", country:"Malta", countryCode:"MT", city:"St. Julian's", appliedAt:"2026-09-25", status:"Aguardando", email:"hr.dragonara@westin.com", stage:"Etapa 4", followUpAt:"2026-10-02", source:"Email", cv:"Fabrina_Silva_CV_beHOTEL_Malta.pdf" },
  { id:"app-004", candidate:"Fabrina Silva", company:"Distinction Mackenzie Country Hotel", role:"Guest Service Agent", country:"Nova Zelândia", countryCode:"NZ", city:"Twizel", appliedAt:"2026-09-25", status:"Aguardando", email:"gm@distinctiontwizel.co.nz", stage:"Etapa 4", followUpAt:"2026-10-02", source:"Email", cv:"Fabrina_Silva_CV_Hermitage_New_Zealand.pdf" },
  { id:"app-005", candidate:"Fabrina Silva", company:"Scenic Hotel Punakaiki", role:"Hospitality Assistant", country:"Nova Zelândia", countryCode:"NZ", city:"Punakaiki", appliedAt:"2026-09-25", status:"Aguardando", email:"punakaiki@scenichotels.co.nz", stage:"Etapa 4", followUpAt:"2026-10-02", source:"Email", cv:"Fabrina_Silva_CV_Hermitage_New_Zealand.pdf" },
  { id:"app-006", candidate:"Fabrina Silva", company:"Crowne Plaza Auckland", role:"Reservations Agent", country:"Nova Zelândia", countryCode:"NZ", city:"Auckland", appliedAt:"2026-09-25", status:"Aguardando", email:"reservations.cpa@ihg.com", stage:"Etapa 4", followUpAt:"2026-10-02", source:"Email", cv:"Fabrina_Silva_CV_Hermitage_New_Zealand.pdf" },
  { id:"app-007", candidate:"Fabrina Silva", company:"INNSiDE Bugibba by Meliá", role:"Front Office Agent", country:"Malta", countryCode:"MT", city:"Bugibba", appliedAt:"2026-09-25", status:"Aguardando", email:"Innside.Bugibba@melia.com", stage:"Etapa 4", followUpAt:"2026-10-02", source:"Email", cv:"Fabrina_Silva_CV_INNSiDE_Bugibba_Malta.pdf" },
  { id:"app-008", candidate:"Fabrina Silva", company:"be.HOTEL / Bay Street Group", role:"Reservations / Front Office", country:"Malta", countryCode:"MT", city:"St. Julian's", appliedAt:"2026-09-25", status:"Follow-up", email:"vacancies@baystreetgroup.com.mt", stage:"Etapa 4", followUpAt:"2026-09-30", source:"Email", cv:"Fabrina_Silva_CV_beHOTEL_Malta.pdf" },
  { id:"app-009", candidate:"Fabrina Silva", company:"Hotel on Pownal", role:"Front Desk / Guest Services", country:"Canadá", countryCode:"CA", city:"Charlottetown", appliedAt:"2026-09-22", status:"Aguardando", email:"fdm@thehotelonpownal.com", stage:"Etapa 1", source:"Email", cv:"Fabrina_Silva_CV_Hotel_on_Pownal_Canada.pdf", notes:"Candidatura enviada por e-mail; nenhuma resposta recebida até a verificação no Gmail." },
  { id:"app-010", candidate:"Lucas Nascimento", company:"Carristur", role:"Motorista", country:"Portugal", countryCode:"PT", city:"Lisboa", appliedAt:"2026-09-14", status:"Aguardando", email:"recrutamento@carristur.pt", stage:"Anterior", followUpAt:"2026-09-29", source:"Email", cv:"Lucas_Nascimento_CV_Carristur.pdf" },
  { id:"app-011", candidate:"Lucas Nascimento", company:"Marriott", role:"Driver / Guest Transportation", country:"Emirados Árabes", countryCode:"AE", city:"Dubai", appliedAt:"2026-09-14", status:"Aguardando", email:"Portal Marriott", stage:"Anterior", followUpAt:"2026-09-29", source:"Portal", cv:"Lucas_Nascimento_CV_Marriott.pdf" },
  { id:"app-012", candidate:"Lucas Nascimento", company:"Aurora Coop", role:"Motorista de Caminhão", country:"Brasil", countryCode:"BR", city:"Sul do Brasil", appliedAt:"2026-09-15", status:"Entrevista", email:"Portal de Carreiras", stage:"Anterior", source:"Portal", cv:"Lucas_Nascimento_CV_Motorista.pdf" }
];
